[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
true_news = "2HRSoFY9Dru9twGMrpou3pvrqaQfdjhk6GpnK1fqwPNx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/sanjeet/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
